# -*- coding: utf-8 -*-
"""urdu_roman_nmt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEMKUrichgWkFHKlfZkrw6H6BuGe6IR6
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!python -m nmt.train --config configs/exp1.json

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!python -m experiments.run_experiments

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!python -m nmt.infer --ckpt outputs/exp1/best.pt --input "خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے" "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!python -m nmt.infer --ckpt outputs/exp2/best.pt --input "خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے" "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/urdu_roman_nmt
!python -m nmt.infer --ckpt outputs/exp3/best.pt --input "خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے" "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے"